### ISSUE TITLE
ERROR: no such package '@@android_gmaven_r8//jar': The repository '@@android_gmaven_r8' could not be resolved: Repository '@@android_gmaven_r8' is not defined

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_foreign_cc#1128]
[https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3519#018c569d-fa42-4553-947a-54e4ef44e61b](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3519#018c569d-fa42-4553-947a-54e4ef44e61b)

Platform :  Windows, MacOS, Ubuntu

Logs:

```
ERROR: no such package '@@android_gmaven_r8//jar': The repository '@@android_gmaven_r8' could not be resolved: Repository '@@android_gmaven_r8' is not defined
(03:04:46) ERROR: /private/var/tmp/_bazel_buildkite/b3e2bdcd41f0ed3688848cb7f8dfaeca/external/androidsdk/BUILD.bazel:13:25: no such package '@@android_gmaven_r8//jar': The repository '@@android_gmaven_r8' could not be resolved: Repository '@@android_gmaven_r8' is not defined and referenced by '@@androidsdk//:d8_jar_import'
(03:04:46) ERROR: Analysis of target '//cmake_android:app' failed; build aborted: Analysis failed
```

Steps:

```
git clone https://github.com/bazelbuild/rules_foreign_cc.git 
git reset 83aeab38da0475e1c7f7f3b22fb8e956e85c7080 --hard
export USE_BAZEL_VERSION=591d1257c51c2f997e067964878e3a9c7ee1f89c
cd examples
bazel test //... //:third_party_examples_macos_tests -@rules_foreign_cc_examples_third_party//curl:curl_test -
```

CC Greenteam @comius

**Comment by sgowroji** [comment]
CC @[irengrig](https://github.com/irengrig)

**Comment by sgowroji** [comment]
Hi @irengrig, We are moving this pipeline to Disabled CI as the failures are persist from long time. Thanks!

**Comment by jsharpe** [comment]
@sgowroji @irengrig is unresponsive on this repo; its primarily community maintained now by volunteers in their spare time. Most of the breakages occurring in this repo are due to breakages in transitive dependencies in other repos. It has historically been tricky to support both bazel@HEAD and all the active LTS versions at the same time due to other rulesets dropping support for earlier LTS versions which is why fixes for bazel@HEAD have been slow in some instances.

I will look at fixing these issues when I have time so please don't disable the CI testing for bazel@HEAD as this is useful signals for us to know what is going to break in the next version of bazel.

**Comment by jsharpe** [comment]
@sgowroji I've had a quick look at this but its not obvious to me what's causing this; has the android sdk api changed in bazel@HEAD? All that rules_foreign_cc does is configure the android sdk and this has worked in all previous versions of bazel so I suspect that there's been an API change here? Note that I think this is running specifically with bzlmod turned off atm and so it could be a bzlmod vs WORKSPACE issue.

**Comment by jsharpe** [comment]
Should hopefully be fixed by: https://github.com/bazelbuild/rules_foreign_cc/commit/d873cace68b74fa3aea0c8706c92c2998f1c4380 - this is just an incorrect configuration being called when the CI pipeline is launched via the downstream bazel testing.
