### ISSUE TITLE
--action_env=PATH does not appear to import environment's PATH on MacOSX

### ISSUE THREAD

**Issue by curiouserrandy** [bazelbuild/rules_foreign_cc#225]
I'm getting a failure when building https://github.com/envoyproxy/envoy with bazel on Mac OS X 10.13.6 of not being able to find "cmake".  My cmake is installed in /opt/local/bin and when I symlink that (and ninja) to /usr/local/bin the build succeeds.  This would seem to be a problem with the bazel restrictions recently put on the what bazel children can access (in order to make builds more reproducible) but in that case I would expect --action_env=PATH to succeed without the symlinks, and it does not.

I did some additional debugging by putting an "env" in a script at /usr/local/bin and running my build with --action_env=PATH and that had no effect on the path that was output from that script.

The attached zip archive contains four files:
* reproduction.txt: Shell log of simply reproducing the problem in my default environment.
* action-env-failure.txt: Demonstration that --action_env didn't do anything different.
* symlink-success.txt: Demonstration that linking ninja & cmake into /usr/local/bin allowed compilation.
* env-dump.txt: Dump of the environmental variables present when doing a default run.
* env-dump-aciton-env.txt (sic): Running with the above env dump script with --action_env.

Please let me know if there's more debugging I can do to help you get to the root of htis problem.

[bazel-bug.zip](https://github.com/bazelbuild/rules_foreign_cc/files/2858498/bazel-bug.zip)

**Comment by curiouserrandy** [comment]
Sorry, five files (I added the last one after writing most of the report).

**Comment by irengrig** [comment]
Hello @curiouserrandy, thank you for your feedback.
rules_foreign_cc is taking the path of the CMake tool from the custom toolchain with the type "@rules_foreign_cc//tools/build_defs:cmake_toolchain".

This is the intended way of passing the path to CMake (and there is similar toolchain for passign Ninja path), it is exact way to do it, and I was trying to make it as easy as possble for the users of rules_foreign_cc.

Also, as I see, you are running the builds on the Macbook, and we do not use the default environment for running the rules_foreign_cc script there. I am not sure currently if I can change that, the reason is some XCode variables initialization. I will try to investigate that.
The place in the code that manages this: https://github.com/bazelbuild/rules_foreign_cc/blob/4d73887da8d08d04e4e6b3408282dce4c57e3987/tools/build_defs/new_11_2018/framework.bzl#L282

You can define your implementation of the toolchain like this:
`load(":native_tools_toolchain.bzl", "native_tool_toolchain")

native_tool_toolchain(
    name = "local_cmake",
    path = "/opt/local/bin/cmake",
    visibility = ["//visibility:public"],
)
toolchain(
    name = "local_cmake_toolchain",
    toolchain = ":local_cmake",
    toolchain_type = "@rules_foreign_cc//tools/build_defs:cmake_toolchain",
# here you can additionally specify platform constraints, if needed
)
`
and pass the toolchain's target into the initialization of the rules_foreign_cc (which you have in your WORKSPACE file or in the *.bzl file used from WORKSPACE):
`load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies([
    "//<package where it is defined>:local_cmake_toolchain",
])
`
please see similar code in examples' WORKSPACE file:
https://github.com/bazelbuild/rules_foreign_cc/blob/4d73887da8d08d04e4e6b3408282dce4c57e3987/examples/WORKSPACE#L10

**Comment by whitlockjc** [comment]
I am also running into this when building Envoy, as linked above in the referencing issue.  I can't make sense of the suggestion from @irengrig due to garbled formatting of her message but it appears you can add some specialized overrides/rules to work around this.  Any chance we can see an example, or maybe fix the formatting of the previous message so that it's more understandable?

**Comment by alendit** [comment]
The problem goes further than just not being able to find cmake: for example, Apache Arrow is usually built in a conda virtual environment with libraries like Numpy present. Without being able to use `--action-env=PATH` I don't see a way to make `cmake` aware of the existence of the virtual environment.

**Comment by shamsimam** [comment]
I tried configuring a custom `cmake` location using the instructions in https://github.com/bazelbuild/rules_foreign_cc/issues/225#issuecomment-463559607 by editing the `BUILD` and `WORKSPACE` files. 
However, running the bazel build (on the `v1.13.0` branch)q still goes ahead and picks up the `preinstalled_cmake`. I can see the following in the logs:

```
INFO: ToolchainResolution:   Considering toolchain @rules_foreign_cc//tools/build_defs/native_tools:preinstalled_cmake...
INFO: ToolchainResolution:   Considering toolchain //:local_cmake...
INFO: ToolchainResolution:   Considering toolchain @rules_foreign_cc//tools/build_defs/native_tools:preinstalled_cmake...
INFO: ToolchainResolution:   For toolchain type @rules_foreign_cc//tools/build_defs:cmake_toolchain, possible execution platforms and toolchains: {@local_config_platform//:host -> @rules_foreign_cc//tools/build_defs/native_tools:preinstalled_cmake}
````

Any idea what I am doing wrong?

**Comment by shamsimam** [comment]
I had to add the following to get the build to pick my custom `cmake`:
```
rules_foreign_cc_dependencies(["//:local_cmake_toolchain", "@rules_foreign_cc//tools/build_defs:preinstalled_ninja_toolchain"], False)
```

**Comment by shyaamsn** [comment]
@shamsimam Could you please post the entire files that you have made changes to make this work?

**Comment by shamsimam** [comment]
- Add the following to `BUILD`:

```
load(":native_tools_toolchain.bzl", "native_tool_toolchain")

native_tool_toolchain(
  name = "local_cmake",
  path = "/opt/local/bin/cmake",
  visibility = ["//visibility:public"],
)
toolchain(
  name = "local_cmake_toolchain",
  toolchain = ":local_cmake",
  toolchain_type = "@rules_foreign_cc//tools/build_defs:cmake_toolchain",
)


native_tool_toolchain(
  name = "local_ninja",
  path = "/opt/local/bin/ninja",
  visibility = ["//visibility:public"],
)
toolchain(
  name = "local_ninja_toolchain",
  toolchain = ":local_ninja",
  toolchain_type = "@rules_foreign_cc//tools/build_defs:ninja_toolchain",
)
```

- Explicitly configure the cmake and ninja dependecies in `bazel/dependency_imports.bzl`
from
```
rules_foreign_cc_dependencies()
```
to
```
rules_foreign_cc_dependencies(["//:local_cmake_toolchain", "@rules_foreign_cc//tools/build_defs:preinstalled_ninja_toolchain"], False)
```

**Comment by bashims** [comment]
@shamsimam Can you please specify which ```BUILD``` file needs to be updated? Thanks.

**Comment by bashims** [comment]
It seems bonkers that the build system does not honour the PATH variable. Requiring cmake to be in a few select paths is not flexible at all.

**Comment by shamsimam** [comment]
> @shamsimam Can you please specify which `BUILD` file needs to be updated? Thanks.

It is the `BUILD` in the project directory file, e.g. this file: https://github.com/envoyproxy/envoy/blob/master/BUILD.

**Comment by bashims** [comment]
The fix provided by @shamsimam  to get envoy built seems to work. Here is the patch I used to successfully build under CentOS 7. The patch is relative to https://github.com/envoyproxy/envoy/tree/v1.13.1

```diff --git a/bazel/dependency_imports.bzl b/bazel/dependency_imports.bzl
index 051923e31..55683a44e 100644
--- a/bazel/dependency_imports.bzl
+++ b/bazel/dependency_imports.bzl
@@ -9,7 +9,7 @@ load("@upb//bazel:repository_defs.bzl", upb_bazel_version_repository = "bazel_ve
 GO_VERSION = "1.13.5"
 
 def envoy_dependency_imports(go_version = GO_VERSION):
-    rules_foreign_cc_dependencies()
+    rules_foreign_cc_dependencies(["//:local_cmake_toolchain", "//:local_ninja_toolchain"], False)
     go_rules_dependencies()
     go_register_toolchains(go_version)
     rbe_toolchains_config()
diff --git a/bazel/foreign_cc/BUILD b/bazel/foreign_cc/BUILD
index f820d83f1..a947f7a6c 100644
--- a/bazel/foreign_cc/BUILD
+++ b/bazel/foreign_cc/BUILD
@@ -3,6 +3,35 @@ licenses(["notice"])  # Apache 2
 load("//bazel:envoy_build_system.bzl", "envoy_cmake_external", "envoy_package")
 load("@rules_foreign_cc//tools/build_defs:configure.bzl", "configure_make")
 
+load(
+    "@rules_foreign_cc//tools/build_defs/native_tools:native_tools_toolchain.bzl",
+    "native_tool_toolchain",
+)
+
+native_tool_toolchain(
+  name = "local_cmake",
+  path = "/usr/bin/cmake3",
+  visibility = ["//visibility:public"],
+)
+toolchain(
+  name = "local_cmake_toolchain",
+  toolchain = ":local_cmake",
+  toolchain_type = "@rules_foreign_cc//tools/build_defs:cmake_toolchain",
+)
+
+
+native_tool_toolchain(
+  name = "local_ninja",
+  path = "/user/bin/ninja-build",
+  visibility = ["//visibility:public"],
+)
+toolchain(
+  name = "local_ninja_toolchain",
+  toolchain = ":local_ninja",
+  toolchain_type = "@rules_foreign_cc//tools/build_defs:ninja_toolchain",
+)
+
+
 envoy_package()
 
 configure_make(
```

**Comment by bashims** [comment]
@shamsimam  thanks for the follow-up.

**Comment by UebelAndre** [comment]
I actually believe this was resolved and `--action_env` should now work on MacOS. For future readers.
