### ISSUE TITLE
Shared library dependencies aren't properly handled

### ISSUE THREAD

**Issue by rnburn** [bazelbuild/rules_foreign_cc#241]
I'm setting up `configure_build` with something like the following:

```
configure_make(
    name = "pcre",
    lib_source = "@org_pcre//:all",
    static_libraries = ["libpcre.a"],
    shared_libraries = ["libpcre.so.1"],
)

configure_make(
    name = "apache_httpd",
    configure_options = [
        "--with-apr=$EXT_BUILD_DEPS/apr",
        "--with-apr-util=$EXT_BUILD_DEPS/apr_util",
        "--with-pcre=$EXT_BUILD_DEPS/pcre",
    ],
    lib_source = "@org_apache_httpd//:all",
    binaries = [
        "httpd",
    ],
    deps = [
        ":apr",
        ":apr_util",
        ":pcre",
    ],
    visibility = [
        "//visibility:public",
    ],
)
```

If I then create a small test script that runs `apache_httpd/bin/httpd -h`

```
filegroup(
    name = "httpd_binary",
    srcs = [
        ":apache_httpd",
    ],

)

sh_test(
    name = "t",
    srcs = [
        "t.sh",
    ],
    data = [
        ":httpd_binary",
        ":apr",
        ":apr_util",
        ":pcre",
    ],
)
```

I get this error when it runs:
```
apache_httpd/bin/httpd: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
```

**Comment by irengrig** [comment]
Hi @rnburn, thank you so much for this issue.
I tried to modify RPATH for the generated binary ([relevant article](https://amir.rachum.com/blog/2016/09/17/shared-libraries/)), but did not succeed, because the configure script also spoils RPATH with the current build directory value.

So please have a look at a not-so-nice workaround in #247 with setting LD_LIBRARY_PATH to contain needed shared libraries. 
Please note the filegroups with output_group attribute - especially for httpd - as this way we are able to select the originally build directory as a whole.
I was thinking of wrapping it into a rule/function.
I would appreciate if you could suggest a nicer solution.
