### ISSUE TITLE
CMake_script.sh final cp without preserve the link

### ISSUE THREAD

**Issue by qazmichaelgw** [bazelbuild/rules_foreign_cc#430]
cp -L -r --no-target-directory "$BUILD_TMPDIR/$INSTALL_PREFIX" "$INSTALLDIR" 
replace_in_files $INSTALLDIR $BUILD_TMPDIR \${EXT_BUILD_DEPS}
replace_in_files $INSTALLDIR $EXT_BUILD_DEPS \${EXT_BUILD_DEPS}
mkdir -p $EXT_BUILD_ROOT/bazel-out/k8-opt/bin/external/my_realsense/copy_my_realsense/my_realsense
cp -L -r --no-target-directory "$INSTALLDIR" "$EXT_BUILD_ROOT/bazel-out/k8-opt/bin/external/my_realsense/copy_my_realsense/my_realsense" 
touch $EXT_BUILD_ROOT/bazel-out/k8-opt/bin/external/my_realsense/empty_my_realsense.txt
cd $EXT_BUILD_ROOT%    

In the generated CMake_script.sh the final cp should have options -a, otherwise the library will lost link.

Any place to change the template of generating this script?

**Comment by attilaolah** [comment]
FYI the template is located here:

https://github.com/bazelbuild/rules_foreign_cc/blob/ece188f9ab3f75777bf80176d6459a994f709061/tools/build_defs/shell_toolchain/toolchains/impl/default_commands.bzl#L65-L66

And the corresponding `linux_commands.bzl` and `windows_commands.bzl` files:

https://github.com/bazelbuild/rules_foreign_cc/blob/ece188f9ab3f75777bf80176d6459a994f709061/tools/build_defs/shell_toolchain/toolchains/impl/linux_commands.bzl#L65-L66

https://github.com/bazelbuild/rules_foreign_cc/blob/ece188f9ab3f75777bf80176d6459a994f709061/tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl#L65-L66

However, the command already contains `-L`, which is short for `--dereference` which is the opposite of `--no-dereference` which equals to `-d` which is implied by `-a`. So really `-a` in not compatible with the existing `-L` flag.

I think dereferencing symlinks is intentional here, but it may break builds that rely on generating actual symlinks. But those would not be a great fit for Bazel anyway, since it tries to make build artifacts reproducible and symlinks, if absolute, would depend on the execroot. (Relative symlinks should still be OK but I guess we don't support that at the moment.)
