### ISSUE TITLE
Does artifacts really get cached using cmake_external

### ISSUE THREAD

**Issue by systemlogic** [bazelbuild/rules_foreign_cc#438]
I am evaluating if cmake_external support RBE and cache out of the box. Can some one comment?

**Comment by systemlogic** [comment]
HI @irengrig Can you let me know if cmake_external meant to run on RBE? Does it meant to run for MS VS library or we can use cc_library.
-Many Thanks

**Comment by jsharpe** [comment]
Hi @systemlogic,
The rules definitely make use of the cache but with the usual caveats that the outputs of the third party build system should be reproducible and hermetic and not include any absolute paths. By the nature of using an external build system it is easy to break this assumption and hence break bazels caching behaviour.

As to RBE we've just turned on testing for a subset of the test cases in RBE. There is an outstanding issue in getting make to build hermetically via RBE due to RBE not preserving timestamps of the input files.
This can be a general issue for using auto tools based builds on RBE where the remote environment doesn't have auto tools installed. 
Contributions welcome for adding other parts of the auto tools suite as toolchains to the configure_make rules to make this more hermetic and more likely to work on RBE!
