### ISSUE TITLE
outputs written outside CMAKE_PREFIX_PATH

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_foreign_cc#80]
```
CMake Warning at CMakeLists.txt:4 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Can be resolved by adding something like `cache_entries = {"CMAKE_PREFIX_PATH": "/workspace/.bazel/execroot/__main__/bazel-out/k8-fastbuild/genfiles/third_party/cmake/catkin/catkin"}` to the target that depends on the target that generates the above files

Is it possible to write to `/workspace/.bazel/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel_foreign_cc_deps` such that every dependent does not have to specify this cache_entries value?

BUILD:
```
package(default_visibility = ["//visibility:public"])

load("@rules_foreign_cc//tools/build_defs:cmake.bzl", "cmake_external")

filegroup(
    name = "example_src",
    srcs = glob(["src/**"]),
)

cmake_external(
        name = "example",
        lib_source = ":example_src",
        #cache_entries = {"CMAKE_PREFIX_PATH": "/workspace/.bazel/execroot/__main__/bazel-out/k8-fastbuild/genfiles/third_party/cmake/catkin/catkin"},
        deps = [":catkin"],
)

cmake_external( 
        name = "catkin",
        lib_source = "@catkin//:all",
        headers_only = True,
)
```

**Comment by bbarnes52** [comment]
I can resolve my initial issue by writing a macro that wraps cmake_external, leaving this open in case comment#3 needs attention.

**Comment by bbarnes52** [comment]
So for whatever reason catkin-config.cmake does not get written to $EXT_BUILD_DEPS, it appears that it gets written to $INSTALLDIR. Which means if I add $EXT_BUILD_ROOT/bazel-out/k8-fastbuild/genfiles/third_party/catkin/catkin to CMAKE_PREFIX_PATH to every rule that depends on catkin, then everything works as expected (I believe I cannot use $INSTALLDIR because that always points to the current install dir, not the install dir of a targets deps)

Attaching and output file containing stdout and stderr in case you are interested: 
[out.txt](https://github.com/bazelbuild/rules_foreign_cc/files/2381293/out.txt)

**Comment by irengrig** [comment]
Yes, when we build catkin, it gets into INSTALLDIR.
On the next step (I see deps=[":catkin"]) the whole INSTALLDIR of the catkin step should be copied under $EXT_BUILD_DEPS. 
It is in the output that you send: 
symlink_to_dir $EXT_BUILD_ROOT/bazel-out/k8-fastbuild/genfiles/third_party/cmake/catkin/catkin $EXT_BUILD_DEPS
It should work, very strange... I usually only have problems with find_package hints - only setting the CMAKE_PREFIX_PATH is not enough for all cases....

Unfortunately, Catkin itself is quite complicated, I had a look, but it is not for quick experiment.

**Comment by bbarnes52** [comment]
Thanks for taking a look! Is it possible this could be affecting runtime of warm builds as well? Rebuilding a simple ROS package, with no changes, takes around 5 minutes (critical path). Doesn't seem like caching is working correctly. For bazel to meet our requirements this would need to run in O(seconds).

**Comment by irengrig** [comment]
Bazel caches the results of actions, based on the inputs, in our case the inputs are source files and dependencies (both deps and tools_deps).
If no input files changed, and no dependencies, the result should be cached.
By your log, indeed, 19 actions are executed: /workspace/.bazel/sandbox/processwrapper-sandbox/19/execroot/__main__ - the last sandbox.
From the other point of view, if you say it is 5 minutes, this means that, for instance, boost was cached.

But I do not think that caching in this case depends on this specific string parameter, CMAKE_PREFIX_PATH. Should be some other problem.

The other thing is that you should not use the paths like .../k8-fastbuild/ for the build parameters, because this is not portable and this directory is there as a side effect that the rule depends on catkin.
Having many CMake prefixes also reduces performance.

Returning to the initial example,
I was able to build catkin (having all needed Python packages just locally installed) and my primitive example was able to find catkin (but fall further as I do not have the very real example, I just put find_package(catkin REQUIRED)). The only difference is that I am using the filegroup inside the directory with the sources. (Due to the limitation of how we are finding the root directory of the sources)

Is that project open source? Can I get some example to touch? Thank you.

**Comment by bbarnes52** [comment]
Thank you!

Catkin / ROS are open source, here's a good candidate to build in which the issue should manifest: https://github.com/ros/roscpp_core/blob/kinetic-devel/cpp_common/CMakeLists.txt

Here's what my build looks like, this should replicate the issue.
```
cmake_external(
        name = "cpp_common",
        lib_source = "@cpp_common//:all",
        shared_libraries = ["libcpp_common.so"],
        deps = [ 
          ":catkin",
          ":console_bridge",
          ":boost",
        ],  
)

cmake_external(
        name = "console_bridge",
        lib_source = "@console_bridge//:all",
        shared_libraries = ["libconsole_bridge.so"]
)

cmake_external(
        name = "catkin",
        lib_source = "@catkin//:all",
        headers_only = True,
)

boost_build(
    name = "boost",
    lib_source = "@boost//:all"
)
```

And relevant WORKSPACE details:
```
http_archive(
        name = "console_bridge",
        build_file_content = all_content,
        strip_prefix = "console_bridge-0.4.0",
        urls = ["https://github.com/ros/console_bridge/archive/0.4.0.tar.gz"],
)

http_archive(
        name = "catkin",
        build_file_content = all_content,
        strip_prefix = "catkin-0.7.14",
        urls = ["https://github.com/ros/catkin/archive/0.7.14.tar.gz"],
)

http_archive(
        name = name,
        build_file_content = """filegroup(name = "all", srcs = glob(["cpp_common/**"]), visibility = ["//visibility:public"])""",
        strip_prefix = "roscpp_core-0.6.11",
        urls = ["https://github.com/ros/roscpp_core/archive/0.6.11.tar.gz"],
)
```

**Comment by irengrig** [comment]
I am getting the following error:
Traceback (most recent call last):
  File "/tmp/tmp.vQvj3IPuPD/catkin_generated/generate_cached_setup.py", line 20, in <module>
    from catkin.environment_cache import generate_environment_script
ImportError: No module named catkin.environment_cache
CMake Error at <...>/.cache/bazel/_bazel_ichern/3ef9cfc3a9b14f5d67990ffd01552d35/sandbox/linux-sandbox/1/execroot/rules_foreign_cc/bazel_foreign_cc_deps_cpp_common/catkin/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/tmp/tmp.vQvj3IPuPD/catkin_generated/generate_cached_setup.py") returned
  error code 1
Call Stack (most recent call first):
  <...>/.cache/bazel/_bazel_ichern/3ef9cfc3a9b14f5d67990ffd01552d35/sandbox/linux-sandbox/1/execroot/rules_foreign_cc/bazel_foreign_cc_deps_cpp_common/catkin/share/catkin/cmake/all.cmake:198 (safe_execute_process)
  <...>/.cache/bazel/_bazel_ichern/3ef9cfc3a9b14f5d67990ffd01552d35/sandbox/linux-sandbox/1/execroot/rules_foreign_cc/bazel_foreign_cc_deps_cpp_common/catkin/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:6 (find_package)

Looks like when I just build catkin from sources with my script, it is not enough for the Catkin CMake scripts, they are missing some environment setup.
Do you perform any additional actions for the Catkin setup?

And again, is the idea to just use Catkin's scripts and actually invoke CMake?
It is possible to reuse functionality from rules_foreign_cc to invoke Catkin instead of CMake and use the results in Bazel, I think that would be the good way.

**Comment by bbarnes52** [comment]
I think you need to `apt-get install python-catkin-pkg`. Here is the complete list of packages I install:
```
apt-get install -y 
  python-empy \
  python-catkin-pkg \
  python-dev \
  python-numpy \
  python-yaml
```

To your last point, I trust your guidance. One thing to note is that catkin is cmake syntactic sugar, and catkin_make is a /very/ thin wrapper around cmake. It basically just created a directory to use for an out-of-source build, calls cmake from this directory, then calls make.

**Comment by irengrig** [comment]
Thank you for information, I started looking at it, but it will require some time...
Also, I just proved that in this example above only the last failing part starts to rebuild, all the rebuilt targets (boost, catkin etc) are taken from cache. So I do not see the warm-build problems you were mentioning.

**Comment by bbarnes52** [comment]
Thank you! My build is also using cached boost, it could possibly be an issue with my custom macro? (which would no longer be necessary when this issue is resolved)

**Comment by bbarnes52** [comment]
@irengrig is it possible the `symlink_to_dir` function is not WAI? If I add the directory into CMAKE_PREFIX_PATH that is supposed to be symlinked into EXT_BUILD_DEPS the build completes successfully

**Comment by bbarnes52** [comment]
seems like it's WAI ... one thing I noticed is that the error (`could not find console_bridge-config.cmake`) occurs prior to the environment information being logged, and the `env` command is called prior to `symlink_to_dir`. is it possible the symlinking needs to happen sooner?

**Comment by irengrig** [comment]
Sorry, could not return to this earlier. Will try in the next couple of days.

**Comment by bbarnes52** [comment]
thank you! it's very interesting, the error gets logged prior to running the cmake script, yet if you set CMAKE_PREFIX_PATH to the directory that's meant to be symlinked, then the error does not occur, even though CMAKE_PREFIX_PATH is only ever used to generate the cmake script.

**Comment by bbarnes52** [comment]
looks like this was fixed in #138 , thank you!

before I close, would you mind helping me understand what the problem was and how you fixed it?

**Comment by bbarnes52** [comment]
nevermind, this looks like a side-effect of #150

**Comment by bbarnes52** [comment]
@irengrig if you have any time to look at this would greatly appreciate your expertise. I have tried everything I could think of to no avail. Setting CMAKE_PREFIX_PATH to $EXT_BUILD_DEPS/{lib_name} resolves the issue ... I am not sure why $EXT_BUILD_DEPS is not enough, I would think find_package would recursively search directories in the CMAKE_PREFIX_PATH?

**Comment by irengrig** [comment]
@bbarnes52 sorry for the delay with that.
Will try to have a look over the weekend, today I am on the way the whole day...

**Comment by irengrig** [comment]
Well, it works fine for me (finding catkin by some other library code) just with the current version of rules_foreign_cc.
**However, you can modify CMAKE_PREFIX_PATH to have $EXT_BUILD_DEPS/{lib_name}, there is nothing wrong with it, because in this form it correctly refers to the directory under build root**

According to the CMake documentation, it should work with just $EXT_BUILD_DEPS: https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure,
in particular the prefix: `<prefix>/<name>*/(lib/<arch>|lib*|share)/<name>*/(cmake|CMake)/ (W/U)`

But it is rather the question to CMake why it does not find it... 
One of the possible reasons: if the catkin of the non-matching version is already in CMake cache (?? as I understood, if catkin that was found first is of the wrong version, it is just cached and never re-checked): https://cmake.org/pipermail/cmake/2017-August/066169.html

I do not think that it is worth to get deeper in CMake's find_package; since it is ok to adjust CMAKE_PREFIX_PATH for some problematic dependencies, and we have not met so many use cases yet.
So I would not change the default value for now, adding $EXT_BUILD_DEPS/{lib_name} for every library.

**My test example**:
I am using the following test CMakeLists.txt:
`cmake_minimum_required(VERSION 2.8.4)

project(hellolib)

find_package(catkin REQUIRED)`
Of course, it is not producing any result, but we can just inspect where the build is failing.

With this BUILD file, it looks like catkin is found by find_package:
`package(default_visibility = ["//visibility:public"])

load("@rules_foreign_cc//tools/build_defs:cmake.bzl", "cmake_external")

cmake_external(
    name = "catkin",
    cache_entries = {
        "CATKIN_ENABLE_TESTING": "NO",
    },
    headers_only = True,
    lib_source = "@catkin//:all",
)

filegroup(
    name = "find_catkin_srcs",
    srcs = ["CMakeLists.txt"],
)

cmake_external(
    name = "find_catkin",
    lib_source = ":find_catkin_srcs",
    deps = [
        ":catkin",
    ],
)`

the result contains:
`-- Using CATKIN_DEVEL_PREFIX: <...>
-- Using CMAKE_PREFIX_PATH: <...>
-- Using CATKIN_TEST_RESULTS_DIR: <...>
-- catkin 0.7.14
`

If I comment the dependency on catkin out in find_catkin, I am getting:
`CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.`

**Comment by bbarnes52** [comment]
so the issue is that this will not work for transitive dependencies, since the cache_entries value I set for a given target does not propagate to dependent targets

**Comment by bbarnes52** [comment]
was using an older version of cmake *facepalm*

earlier versions did not have the same search procedure

upgrading to 3.12.2 resolved this issue

**Comment by irengrig** [comment]
:D Cool! Happy to hear that!
