### ISSUE TITLE
Request for documentation improvement for configure_in_place field

### ISSUE THREAD

**Issue by garrettkajmowicz-sophos** [bazelbuild/rules_foreign_cc#853]
I'm working with the configure_make() command, and the configure_in_place option isn't clear. I wouldn't worry too much about it except that a number of other commands seem to require that it be set, and that when I do set it I get errors from the configure step about "config.log: Read-only file system" and so on.

Clarification of the difference in operation when this value is True/False (as well as guidance as to when someone might want to use it) would be greatly appreciated.

**Comment by jsharpe** [comment]
By default `configure_make` attempts to do an out of tree build. This is broken in some codebases and they require you do run configure within the source tree itself. This is the idea behind `configure_in_place`, however it symlinks most of the source files into the build directory and so if your configure scripts attempt to modify any of the files from that original tree then it will fail as you are seeing. It probably needs to be switched to use a copy rather than a symlink to fix this behaviour.

**Comment by jsharpe** [comment]
In fact I previously started to fix this: https://github.com/bazelbuild/rules_foreign_cc/pull/596 but never landed the PR

**Comment by garrettkajmowicz-sophos** [comment]
I would definitely be in-favor of seeing this land.
