### ISSUE TITLE
Issue with log4cxx build

### ISSUE THREAD

**Issue by fuhailin** [bazelbuild/rules_foreign_cc#864]
From now, the latest log4cxx version is 0.12.1, and only support building method is cmake, so I try to update the example of log4cxx in this repo.

When I tried to use the cmake rules to replace the configure_make rules, I got errors that `APR_INCLUDE_DIR (missing: APR_LIBRARIES)`, so how could I pass the APR deps to the cmake rules when build log4cxx?

Could you please update the example of building log4cxx in this repo?

Thanks.

**Comment by jheaff1** [comment]
It was an intentional decision to use an older version of log4cxx (which uses `configure_make`) as the build of log4cxx provides a regression test for fixes to #344 (i.e `configure_make`) with transitive dependencies.

To resolve your issue, I suggest looking at the [curl example](https://github.com/bazelbuild/rules_foreign_cc/blob/50ee9979e60e8db38e10de45d2c60873a210bf55/examples/third_party/curl/BUILD.curl.bazel#L19), which depends on the build of OpenSSL. 

You can set the CMake cache variable `APR_INCLUDE_DIR` To `$$EXT_BUILD_DEPS$$/apr`
