### ISSUE TITLE
Got "conflicting types for 'strncasecmp'" when using rules_foreign_cc with cc_toolchain_config.

### ISSUE THREAD

**Issue by JasonLiuTruck** [bazelbuild/rules_foreign_cc#926]
[rules_foreign_cc_bug.tar.gz](https://github.com/bazelbuild/rules_foreign_cc/files/8876161/rules_foreign_cc_bug.tar.gz)
I got known error when using rules_foreign_cc. Have any solutions for this bug?

**Comment by JasonLiuTruck** [comment]
Command: bazel build //example:srt_example
![image](https://user-images.githubusercontent.com/101796052/173002368-13d04ec8-b29a-4ff1-af33-63e77fd3edd3.png)

**Comment by jsharpe** [comment]
Is this on Apple Silicon?

**Comment by JasonLiuTruck** [comment]
@jsharpe No. I test on Ubuntu 20.04@X86_64 and WSL-Ubuntu@X86_64, the results are same.

**Comment by jsharpe** [comment]
Ok, tracked this down; this is due to your custom toolchain enabling the flag -Werror. This causes the configure tests that rely on generating compiler warnings to fail, meaning a needed define isn't set for the build of GNUMake.

I'd suggest that you configure your host_crosstool_top to point to a toolchain which doesn't have -Werror turned on.

For future reference it'd be useful when reporting bugs the fact that you are configuring your own toolchain. Note I've only tested this with gcc as I don't have a system setup with the same clang install that you do so there may be other issues if you are using clang for the host/exec compiler.

**Comment by aaron-michaux** [comment]
It seems to me that foreign_cc is trying to do too much, and ends up second guessing the developer. There's a lot of bad makefiles and cmake out there. Being able to override and remove CFLAGS, etc., would be helpful.

**Comment by ankit-agarwal1999** [comment]
To close the loop, for folks who still want to use "-Werror", you can apply this patch to cause make tool to work: 

```

diff --git foreign_cc/built_tools/make_build.bzl foreign_cc/built_tools/make_build.bzl
index 0baaa5c..9b74207 100644
--- foreign_cc/built_tools/make_build.bzl
+++ foreign_cc/built_tools/make_build.bzl
@@ -46,7 +46,7 @@ def _make_tool_impl(ctx):
         cc_path = tools_info.cc
         cflags = flags_info.cc
         sysroot_cflags = [flag for flag in cflags if flag.startswith("--sysroot=")]
-        non_sysroot_cflags = [flag for flag in cflags if not flag.startswith("--sysroot=")]
+        non_sysroot_cflags = [flag for flag in cflags if not flag.startswith("--sysroot=")] + ["-Wno-error"]
 
         ld_path = tools_info.cxx_linker_executable
         ldflags = flags_info.cxx_linker_executable

```
